version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bookstore-db
    environment:
      POSTGRES_DB: Bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: parola
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

  app:
    build: .
    container_name: bookstore-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Bookstore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: parola
    ports:
      - "8080:8080"
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  postgres_data: