version: '3.8'

services:
  # EUREKA SERVER
  eureka-server:
    image: steeltoeoss/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - bookstore-network

  # Database
  postgres:
    image: postgres:15-alpine
    container_name: bookstore-db
    environment:
      POSTGRES_DB: Bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: parola
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Bookstore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: parola
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_APPLICATION_NAME: auth-service
      BOOKSTORE_SERVICE_URL: http://bookstore-service:8082  # ADĂUGAT
    ports:
      - "8081:8081"
    networks:
      - bookstore-network

  # Bookstore Service
  bookstore-service:
    build: ./bookstore-service
    container_name: bookstore-service
    depends_on:
      - postgres
      - eureka-server
      - auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Bookstore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: parola
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_APPLICATION_NAME: bookstore-service
      AUTH_SERVICE_URL: http://auth-service:8081
    ports:
      - "8082:8082"
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  postgres_data: